name: rick_and_morty_dex
description: "A Rick and Morty dex"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobx: ^2.5.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2

dev_dependencies:
  mobx_codegen: ^2.7.0
  build_runner: ^2.4.11
  flutter_mobx: ^2.3.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/default_characters/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
